### PR TITLE
Update introduction

### PR DESCRIPTION
**Pull request by tobyhodges**
I noticed that the opening paragraph of the intro doesn't make a lot of sense now that the mention of the old, old title has been removed. I've tried to reword here. Happy to supplement this PR with additional commits if you think there's anything else that needs updating in the introduction.

### CODE REVIEW

**Comment by tobyhodges** [comment]
Oh, also: I should check the etiquette on submitting PRs now that we've switch to LaTeX - should I have built the book first. (Rhetorical question - I will check the contributing guidelines...)

**Comment by tobyhodges** [comment]
Ok, I got a 404 from http://js4ds.org/en/contributing/. @gvwilson should one run `make [html|pdf]` to update `docs/index.html`  before I push changes for a PR?

**Comment by tobyhodges** [comment]
Latest commit fixes #67 but updating text of Contributing section of the introduction, to remove the old link.

**Comment by gvwilson** [comment]
Yes, please run `make everything` to update the PDF and HTML versions as part of PRs.

**Comment by tobyhodges** [comment]
Ok, this can be merged after #69 has fixed the issues in the glossary. Also, I think Greg is dropping subtle hints that I should be assigning these to Maya instead of him... :)

**Comment by tobyhodges** [comment]
Ok. I'm done making changes, but happy to fix/update language if you have suggestions. I wasn't super happy with some of the wording in the opening paragraph.

**Comment by MayaGans** [comment]
Looks good to me!

**Comment by gvwilson** [comment]
Whoops - did you mean to merge or to close?

**Pull request merged**
